name: Pages

on:
  push:
    branches:
      - main  # Trigger saat push ke branch main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: recursive  # Jika pakai submodule

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"  # Ganti dengan versi Node.js-mu

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache

      - name: Install Hexo
        run: npm install

      - name: Build Hexo
        run: npm run build  # Akan menjalankan `hexo generate`

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public  # Folder hasil build Hexo

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4